<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

// Create shortcuts to some parameters.
$params  = $this->item->params;
$images  = json_decode($this->item->images);
$urls    = json_decode($this->item->urls);
$canEdit = $params->get('access-edit');
$user    = JFactory::getUser();
$info    = $params->get('info_block_position', 0);
foreach($this->item->jcfields as $field) :
	// данные
	$itemRawValue[$field->name] = $field->rawvalue;
	// значеине
	$itemFieldVal[$field->name] = $field->value;
	// class
	$itemFieldClass[$field->name] = $field->params->get('render_class');

	$itemFieldName[$field->name] = $field->name;
	// заголовок поля
	$itemFieldTitle[$field->name] = $field->title;
	// группаID
	$itemFieldGroupId[$field->group_id] = $field->group_id;
	// группа
	$itemFieldGroupTitle[$field->group_id] = $field->group_title;
	// параметры
	$itemFieldPar[$field->name] = $field->fieldparams;

	foreach($itemFieldGroupId as $itemGroupId) :
		$db = JFactory::getDBO();
		$query = $db->getQuery(true);
		$query = 'SELECT `description` FROM `#__fields_groups` WHERE `id`='.$itemGroupId.' AND `state`>0';
		$db->setQuery($query);
		$res= $db->loadObjectList();
		foreach ($res as $res_desc) : ?>
	<?php $fieldDesc[$field->group_id] = $res_desc->description; ?>
		<?php endforeach; 
	endforeach;

endforeach;
// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));
JHtml::_('behavior.caption');

?>
<div class="page-article article<?=$this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="<?=($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />
	<?php if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && $this->item->paginationrelative) {
		echo $this->item->pagination; } ?>
	
	<?php if ($this->params->get('show_page_heading')) : ?>
		<h1 class="page-header"><?=$this->escape($this->params->get('page_heading')); ?></h1>
	<?php endif;?>

	<?php if ($params->get('show_title') || $params->get('show_author')) : ?>
		<h1 class="page-subheading" itemprop="headline"><?php if ($params->get('show_title')) :  ?><?=$this->escape($this->item->title);?><?php endif; ?><?php if ($this->item->state == 0) : ?><span class="alert alert-warning"><?=JText::_('JUNPUBLISHED'); ?></span><?php endif; ?><?php if (strtotime($this->item->publish_up) > strtotime(JFactory::getDate())) : ?><span class="alert alert-warning"><?=JText::_('JNOTPUBLISHEDYET'); ?></span><?php endif; ?><?php if ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate()) : ?><span class="alert alert-warning"><?=JText::_('JEXPIRED'); ?></span><?php endif; ?></h1>
	<?php endif; ?>
	<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
	<?=$this->item->event->afterDisplayTitle; ?>
	<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
	<?=$this->item->event->beforeDisplayContent; ?>

	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '0')) || ($params->get('urls_position') == '0' && empty($urls->urls_position)))
			|| (empty($urls->urls_position) && (!$params->get('urls_position')))) : ?>
		<?=$this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php if ($params->get('access-view')) : ?>
	
	<?php if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && !$this->item->paginationrelative) : echo $this->item->pagination; endif; ?>

	<div class="item">
	<?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
		<div class="item_content">
	<?php endif; ?>
		<?php if($this->item->category_alias == 'news') : 
			echo JLayoutHelper::render('joomla.content.article_image', $this->item);
		 else : 
			echo JLayoutHelper::render('joomla.content.full_image', $this->item); 
		endif; ?>

		<?php if (isset ($this->item->toc)) :
			echo $this->item->toc;
		endif; ?>
	<?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
			<?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>
			<?=$this->item->tagLayout->render($this->item->tags->itemTags); ?>
		</div>
	<?php endif; ?>
		<?php if($itemFieldGroupId['2']) : ?>
			<?php if(!empty($itemFieldVal['headtitle']) || !empty($itemRawValue['linking'])) : ?>
			<h3 class="page-subtitle" itemprop="name">
			<?php if(!empty($itemFieldVal['linking'])) : ?>
				<a href="<?=$itemRawValue['linking']?>"><?=$itemFieldVal['headtitle']; ?></a>
			<?php else : ?>
				<?=$itemFieldVal['headtitle']; ?>
			<?php endif; ?>
			</h3>
			<?php endif; ?>
		<?php endif; ?>
		<div class="text" itemprop="articleBody">
		<?php if($this->item->category_alias == 'projects' && !empty($this->item->text)) : ?>
			<h4><?=JText::_('PROJECT_DESCRIPTION');?></h4>
		<?php endif; ?>
			<?=$this->item->text; ?>
			<?php if(!empty($itemFieldVal['year']) && isset($itemFieldVal['year'])): ?>
				<p><?=JText::_('PROJECT_REALIZE').$itemFieldVal['year'] .JText::_('PROJECT_YEAR') ; ?></p> 
			<?php endif; ?>
		</div>
	</div>
	<?php if($itemFieldGroupId['4'] || $itemFieldGroupId['5'] || $itemFieldGroupId['6'] || $itemFieldGroupId['7']) : ?>
	<div class="tabs">
		<nav class="nav tabs_nav" role="tablist">
			<?php if(!empty($itemFieldVal['thickness'] || $itemFieldVal['size'] || $itemFieldVal['speed'] || $itemFieldVal['control'] || $itemFieldVal['options'])) : ?>
				<a class="tabs_nav-item nav-link active" data-toggle="list" href="#tab-<?=$itemFieldGroupId['4']; ?>" role="tab"><?=$itemFieldGroupTitle['4'];?></a>
			<?php endif; ?>
			<?php if(!empty($itemFieldVal['color'])) : ?>
				<a class="tabs_nav-item nav-link" data-toggle="list" href="#tab-<?=$itemFieldGroupId['5']; ?>" role="tab"><?=$itemFieldGroupTitle['5'];?></a>
			<?php endif; ?>
			<?php if(!empty($itemFieldVal['superiority'])) : ?>
				<a class="tabs_nav-item nav-link" data-toggle="list" href="#tab-<?=$itemFieldGroupId['6']; ?>" role="tab"><?=$itemFieldGroupTitle['6'];?></a>
			<?php endif; ?>
			<?php if(!empty($itemFieldVal['documentation'])) : ?>
				<a class="tabs_nav-item nav-link" data-toggle="list" href="#tab-<?=$itemFieldGroupId['7']; ?>" role="tab"><?=$itemFieldGroupTitle['7'];?></a>
			<?php endif; ?>
		</nav>
		<div class="tabs_content">
			<?php if(!empty($itemFieldVal['thickness'] || $itemFieldVal['size'] || $itemFieldVal['speed'] || $itemFieldVal['control'] || $itemFieldVal['options'])) : ?>
			<div class="tabs_content-pane active" id="tab-<?=$itemFieldGroupId['4']; ?>" role="tabpanel">
				<h3><?=$fieldDesc['4'];?></h3>
				<?php if(!empty($itemFieldVal['thickness'])) : ?>
				<?php $itemRawThickness = json_decode($itemRawValue['thickness'], true); ?>
				<div class="pane <?=$itemFieldName['thickness'];?>">
					<?php if(!empty($itemFieldVal['thicknesscaption'])) : ?>
						<span class="caption"><?=$itemFieldVal['thicknesscaption']; ?></span>
					<?php endif; ?>
					<?php foreach ($itemRawThickness as $itemThickness) : ?>
					<dl class="desc">
					<?php if (!empty($itemThickness['title'])) : ?>
						<dt class="title"><?=$itemThickness['title']; ?></dt>
					<?php endif; ?>
					<?php if (!empty($itemThickness['value'])) : ?>
						<dd class="value"><?=$itemThickness['value']; ?></dd>
					<?php endif;?>
					</dl>
					<?php endforeach; ?>
				</div>
				<?php endif; ?>

				<?php if(!empty($itemFieldVal['size'])) : ?>
					<div class="pane <?=$itemFieldName['sizecaption'];?>">
					<?php if(!empty($itemFieldVal['sizecaption'])) : ?>
						<span class="caption"><?=$itemFieldVal['sizecaption']; ?></span>
					<?php endif; ?>
					<?php $itemRawSize = json_decode($itemRawValue['size'], true); ?>
					<?php foreach ($itemRawSize as $itemSize) : ?>
						<?php if (!empty($itemSize['title']) && !empty($itemSize['value'])) : ?>
						<dl class="desc">
							<dt class="title"><?=$itemSize['title']; ?></dt>
							<dd class="value"><?=$itemSize['value']; ?></dd>
						</dl>
						<?php endif;?>
					<?php endforeach; ?>
					</div>	
				<?php endif; ?>

				<?php if(!empty($itemFieldVal['speed'])) : ?>
					<div class="pane <?=$itemFieldName['speed'];?>">
					<?php if(!empty($itemFieldVal['speedcaption'])) : ?>
						<span class="caption"><?=$itemFieldVal['speedcaption']; ?></span>
					<?php endif; ?>
						<?php $itemRawSpeed = json_decode($itemRawValue['speed'], true); ?>
						<?php foreach ($itemRawSpeed as $itemSpeed) : ?>
						<dl class="desc">
							<?php if (!empty($itemSpeed['title'])) : ?>
								<dt class="title"><?=$itemSpeed['title']; ?></dt>
							<?php endif;?>
							<?php if (!empty($itemSpeed['value'])) : ?>
								<dd class="value"><?=$itemSpeed['value']; ?></dd>
							<?php endif;?>
						</dl>
						<?php endforeach; ?>
					</div>
				<?php endif; ?>

				<?php if(!empty($itemFieldVal['control'])) : ?>
				<div class="pane <?=$itemFieldName['control'];?>">
					<span class="caption"><?=$itemFieldTitle['control']; ?></span>
					<div class="desc">
						<p class="text"><?=$itemFieldVal['control']; ?></p>
					</div>
				</div>
				<?php endif; ?>

				<?php if(!empty($itemFieldVal['options'])) : ?>
				<div class="pane <?=$itemFieldName['options'];?>">
					<span class="caption"><?=$itemFieldTitle['options']; ?></span>
					<div class="desc">
						<p class="text"><?=$itemFieldVal['options']; ?></p>
					</div>
				</div>
				<?php endif; ?>
			</div>
			<?php endif; ?>

			<?php if(!empty($itemFieldVal['color'])) : ?>
			<div class="tabs_content-pane" id="tab-<?=$itemFieldGroupId['5']; ?>" role="tabpanel">
				<h3><?=$fieldDesc['5'];?></h3>
				<table class="table <?=$itemFieldName['color'];?>">
				<?php if(!empty($itemFieldVal['colortext'])) : ?>
					<caption class="caption"><?=$itemFieldVal['colortext']; ?></caption>
				<?php endif; ?>
					<tbody>
						<?php $itemRawColor = json_decode($itemRawValue['color'], true); ?>
						<?php foreach ($itemRawColor as $itemColor) : ?>
						<tr>
							<?php if (!empty($itemColor['title'])) : ?>
								<td class="title"><?=$itemColor['title']; ?></td>
							<?php endif; ?>
							<?php if (!empty($itemColor['value'])) : ?>
								<td class="square" style="background-color:<?=$itemColor['value']; ?>;"></td>
							<?php endif; ?>
							<?php if (!empty($itemColor['text'])) : ?>
								<td class="text"><?=$itemColor['text']; ?></td>
							<?php endif; ?>
						</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</div>
			<?php endif; ?>

			<?php if(!empty($itemFieldVal['superiority'])) : ?>
			<div class="tabs_content-pane" id="tab-<?=$itemFieldGroupId['6']; ?>" role="tabpanel">
				<h3><?=$fieldDesc['6'];?></h3>
				<?php $itemRawSuper = json_decode($itemRawValue['superiority'], true); ?>
				<div class="<?=$itemFieldName['speedcaption'];?>">
					<ul class="desc">
					<?php foreach ($itemRawSuper as $itemSuper) : ?>
						<li class="text"><?=$itemSuper['text']; ?></li>
					<?php endforeach; ?>
					</ul>
				</div>
			</div>
			<?php endif; ?>
			<?php if(!empty($itemFieldVal['documentation'])) : ?>
			<div class="tabs_content-pane" id="tab-<?=$itemFieldGroupId['7']; ?>" role="tabpanel">
				<h3><?=$fieldDesc['7'];?></h3>
				<?php $itemRawDoc = json_decode($itemRawValue['documentation'], true); ?>
				<a href="<?=$itemDoc['value']; ?>" class="<?=$itemFieldName['documentation'];?>" target="_blank" >
					<?php foreach ($itemRawDoc as $itemDoc) : ?>
					<dl class="desc">
						<dt class="title"><?=$itemDoc['title']; ?></dt>
						<dd class="value"></dd>
					</dl>
					<?php endforeach; ?>
				</a>
			</div>
			<?php endif; ?>
		</div>
	</div>
	<?php endif; ?>
	<?php if($this->item->category_alias == 'products') : ?>
			<?php echo JLayoutHelper::render('joomla.content.tags_sql', $this->item);  ?>
		<?php endif; ?>
	<?php $itemRawImg = json_decode($itemRawValue['imgallery'], true);
	if (isset($itemRawImg) && !empty($itemRawImg)) : ?>
	<div class="gallery<?=$itemFieldClass['imgallery']; ?>" >
		<?php foreach ($itemRawImg as $key => $itemImg) : ?>
		<div class="gallery_col">
			<?php if (!empty($itemImg['mini']) && !empty($itemImg['big'])) : ?>
			<a href="<?=$itemImg['big']; ?>" <?php if (!empty($itemImg['title'])) : ?> title="<?=htmlspecialchars($itemImg['title']); ?>"<?php endif; ?> >
				<img src="<?=$itemImg['mini']; ?>" 
			<?php elseif(!empty($itemImg['big'])) : ?>
				<img src="<?=$itemImg['big']; ?>" 
			<?php else : ?>
				<img src="<?=$itemImg['mini']; ?>" 
			<?php endif; ?>
			<?php if (!empty($itemImg['alt'])) : ?>
				alt="<?=htmlspecialchars($itemImg['alt']); ?>" 
			<?php else : ?>
				alt="<?=$this->item->title; ?>" 
			<?php endif; ?>
				class="image"/>
			<?php if (!empty($itemImg['mini']) && !empty($itemImg['big'])) : ?>
				</a>
			<?php endif; ?>
		</div>
		<?php endforeach; ?>
	</div>
	<?php endif;  ?>

	<?php $itemRawVideo = json_decode($itemRawValue['video'], true);
	if (isset($itemRawVideo) && !empty($itemRawVideo)) : ?>
	<div class="video<?=$itemFieldClass['video']; ?>" >
	<?php foreach ($itemRawVideo as $key => $itemVideo) : 
		if (isset($itemVideo['title']) && !empty($itemVideo['title'])) : ?>
			<h3><?=$itemVideo['title']; ?></h3>
		<?php endif;  ?>
		<p><a href="<?=$itemVideo['link']; ?>" target="_blank" rel="nofollow noopener noreferrer" class="youtube" width="100%" height="560">
		<img src="<?php if (isset($itemVideo['img']) && !empty($itemVideo['img'])) : echo $itemVideo['img']; else : echo $tpath.'/images/youtube.jpg'; endif;  ?>"
		alt="youtube-hangar-doors">
		<i class="fab fa-youtube" aria-hidden="true"></i></a></p>
	<?php endforeach; ?>
	</div>
	<?php endif;  ?>

	<?php // Todo Not that elegant would be nice to group the params ?>
	<?php $useDefList = ($params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
	|| $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam); ?>

	<?php if (!$useDefList && $this->print) : ?>
		<div id="pop-print" class="btn hidden-print">
			<?=JHtml::_('icon.print_screen', $this->item, $params); ?>
		</div>
	<?php endif; ?>
	
	<?php if (!$this->print) : ?>
		<?php if ($canEdit || $params->get('show_print_icon') || $params->get('show_email_icon')) : ?>
			<?=JLayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item, 'print' => false)); ?>
		<?php endif; ?>
	<?php else : ?>
		<?php if ($useDefList) : ?>
			<div id="pop-print" class="btn hidden-print">
				<?=JHtml::_('icon.print_screen', $this->item, $params); ?>
			</div>
		<?php endif; ?>
	<?php endif; ?>

	<?php if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && !$this->item->paginationrelative) :
		echo $this->item->pagination; ?>
	<?php endif; ?>
	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '1')) || ($params->get('urls_position') == '1'))) : ?>
		<?=$this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php // Дополнительный вводный текст тизера для гостей ?>
	<?php elseif ($params->get('show_noauth') == true && $user->get('guest')) : ?>

		<?=JLayoutHelper::render('joomla.content.intro_image', $this->item); ?>

		<?=JHtml::_('content.prepare', $this->item->introtext); ?>

		<?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
			<?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
			<?=JLayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
		<?php endif; ?>
		<?php if ($info == 1 || $info == 2) : ?>
			<?php if ($useDefList) : ?>
				<?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
				<?=JLayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
			<?php endif; ?>
			<?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
			<?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>
				<?=$this->item->tagLayout->render($this->item->tags->itemTags); ?>
			<?php endif; ?>
		<?php endif; ?>
		
		<?php // Дополнительная ссылка, чтобы позволить им зарегистрироваться, чтобы увидеть всю статью. ?>
		<?php if ($params->get('show_readmore') && $this->item->fulltext != null) : ?>
		<?php $menu = JFactory::getApplication()->getMenu(); ?>
		<?php $active = $menu->getActive(); ?>
		<?php $itemId = $active->id; ?>
		<?php $link = new JUri(JRoute::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false)); ?>
		<?php $link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
		<p class="readmore">
			<a href="<?=$link; ?>" class="register">
			<?php $attribs = json_decode($this->item->attribs); ?>
			<?php
			if ($attribs->alternative_readmore == null) :
				echo JText::_('COM_CONTENT_REGISTER_TO_READ_MORE');
			elseif ($readmore = $attribs->alternative_readmore) :
				echo $readmore;
				if ($params->get('show_readmore_title', 0) != 0) :
					echo JHtml::_('string.truncate', $this->item->title, $params->get('readmore_limit'));
				endif;
			elseif ($params->get('show_readmore_title', 0) == 0) :
				echo JText::sprintf('COM_CONTENT_READ_MORE_TITLE');
			else :
				echo JText::_('COM_CONTENT_READ_MORE');
				echo JHtml::_('string.truncate', $this->item->title, $params->get('readmore_limit'));
			endif; ?>
			</a>
		</p>
		<?php endif; ?>
	<?php endif; ?>
	<?php if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && $this->item->paginationrelative) :
		echo $this->item->pagination; ?>
	<?php endif; ?>
	<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
	<?=$this->item->event->afterDisplayContent; ?>
</div>
